from __future__ import annotations


DATABASE_ID = "trade_data"

SYNONYMS: dict[str, list[str]] = {
    "trade_data.stock_daily.symbol": ["股票代码", "证券代码", "代码"],
    "trade_data.stock_daily.stock_name": ["股票名称", "证券名称", "名称"],
    "trade_data.stock_daily.trade_date": ["交易日期", "交易日", "日期"],
    "trade_data.stock_daily.close": ["收盘价", "收盘价格"],
    "trade_data.stock_daily.volume": ["成交量", "交易量"],
    "trade_data.stock_daily.turnover": ["成交额", "交易额"],
    "trade_data.stock_daily.total_market_cap": ["总市值", "市值"],
    "trade_data.stock_daily.float_market_cap": ["流通市值"],
    "trade_data.stock_daily.industry_level_1": ["一级行业", "申万一级行业"],
    "trade_data.stock_daily.industry_level_2": ["二级行业", "申万二级行业"],
    "trade_data.stock_daily.industry_level_3": ["三级行业", "申万三级行业"],
    "trade_data.financial_statement.symbol": ["股票代码", "证券代码", "代码"],
    "trade_data.financial_statement.report_date": ["报告期", "财报日期", "报告日期"],
    "trade_data.financial_statement.publish_date": ["披露日期", "公告日期", "发布日期"],
    "trade_data.financial_statement.total_assets": ["资产总计", "总资产"],
    "trade_data.financial_statement.total_liabilities": ["负债合计", "总负债"],
    "trade_data.financial_statement.total_owner_equity": ["所有者权益", "净资产", "股东权益"],
    "trade_data.financial_statement.operating_revenue": ["营业总收入", "营业收入", "营收"],
    "trade_data.financial_statement.net_profit": ["净利润"],
    "trade_data.financial_statement.parent_net_profit": ["归母净利润"],
    "trade_data.financial_statement.operating_cash_flow": ["经营活动现金流净额", "经营现金流"],
    "trade_data.index_daily.index_code": ["指数代码", "大盘代码", "代码"],
    "trade_data.index_daily.trade_date": ["交易日期", "交易日", "日期"],
    "trade_data.index_daily.open": ["开盘点位", "开盘指数", "开盘价"],
    "trade_data.index_daily.high": ["最高点位", "最高指数", "最高价"],
    "trade_data.index_daily.low": ["最低点位", "最低指数", "最低价"],
    "trade_data.index_daily.close": ["收盘点位", "收盘指数", "收盘价"],
    "trade_data.index_daily.volume": ["指数成交量", "成交量", "交易量"],
    "trade_data.index_daily.turnover": ["指数成交额", "成交额", "交易额"],
    "trade_data.stock_etf_trading_data.trade_date": ["交易日期", "交易日", "日期"],
    "trade_data.stock_etf_trading_data.fund_name": ["基金名称", "ETF名称"],
    "trade_data.stock_etf_trading_data.fund_code": ["基金代码", "ETF代码", "证券代码"],
    "trade_data.stock_etf_trading_data.close": ["收盘价", "收盘价格"],
    "trade_data.stock_etf_trading_data.volume": ["成交量", "交易量"],
    "trade_data.stock_etf_trading_data.turnover": ["成交额", "交易额"],
    "trade_data.stock_etf_trading_data.cumulative_nav": ["累计单位净值", "累计净值"],
    "trade_data.stock_etf_trading_data.unit_nav": ["单位净值", "基金净值"],
    "trade_data.stock_etf_trading_data.backward_adjustment_factor": ["后复权因子", "复权因子"],
    "trade_data.stock_etf_trading_data.adjusted_nav": ["复权单位净值", "复权净值"],
    "trade_data.stock_etf_trading_data.turnover_rate": ["换手率"],
    "trade_data.stock_etf_trading_data.fund_category": ["基金分类", "基金类型"],
    "trade_data.stock_etf_trading_data.detailed_category": ["详细分类", "细分类型"],
    "trade_data.stock_etf_trading_data.total_fund_shares": ["基金份额合计", "总份额"],
    "trade_data.stock_etf_trading_data.exchange_tradable_shares": ["场内流通份额", "流通份额"],
}
